language: bash

sudo: required

before_install:
  - sudo ./.ci/setup.sh

script:
  - sudo ./.ci/build.sh

before_deploy:
  - sudo ./.ci/deploy.sh

deploy:
  provider: releases
  api_key:
    secure: pUrHhrroypJpRJ9AJnxdzuktAv/ToJRtB4qxxjnNBWmBWDIhw2SQbcEODDOVtnxWaVEzKMqEpkr211gAZ/vYVG7WSawQNZLtCaohpicjutOMftu1ZcnGPSMG5jctYY1SIPnLDCPp4w2TdoeLPP3FrSrwugjmAUgZEJclf69en1+dafZZYII/nQGHALfupeWzoADDGYNfMbXethrQai7Wt24w6itopuVLmH/Cvaj4zpDvaXIty7kaF+ihb3Vy6eZof8U3CAVIFqEdsBmfYnjQ285H2RcFkV67YVQn0L6xtHpz4yikyX2FwToUDkrt9WSHuVZJoK1oVW3paNxTYlpF48+BQ7C3ZIMa1008D5yJVqizWsLlnRKf3iNC5i0f5tpJnHwuTfOEhKW8hDh18C54GmYGBzNl+Zhi3mp5LPzBDhTy1EYf9jsr1Lbmsdk0EZhyDK3BXcD8nNKNl3W0ynLpBStMCM5X079Tbjhc0jprtS/aHhfO4zaYuanAXd/imLtBm17Fe0LSf93QhKoQ8uKip1BY37fGM3p7FO5NiCoYk6ThLcgZow3FoZqdsdVZb6ipVDYwucfUYRT61v2lnKzMXNlV27JAF9AMk/UGoF3FcJbwBmjNxCg7nX4KrDzEYfRXLRstJRgJAlqJ2VgptgNozgOsR2s4p+sxLXxIVrPIN40=
  file_glob: true
  file: github-release/*
  on:
    tags: true
